import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React from 'react';
import NavBar from '@/app/[lang]/[location]/_components/NavBar/NavBar';
import { i18n, Locale } from '@/i18n-config';
import { getDictionary } from '@/get-dictionary';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export async function generateStaticParams() {
    return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function RootLayout({
    params,
    children,
}: {
    params: {
        lang: Locale;
    };
    children: React.ReactNode;
}) {
    const localization = await getDictionary(params.lang);
    return (
        <html lang={params.lang}>
            <body className={inter.className}>
                <NavBar localization={localization} />
                {children}
            </body>
        </html>
    );
}
